services:
  - type: web
    name: medical-image-enhancement
    env: python
    buildCommand: pip install -r SRCNN/requirements.txt
    startCommand: gunicorn SRCNN.app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.13
